migrate to sveltekit v1.0
justingolden21/desktopclock pull request #220
Opened 2023-03-21 18:06 UTC by vanillacode314

2023-03-21 19:52 UTC, UltraCakeBakery requested changes

2023-03-21 19:52 UTC, UltraCakeBakery commented on package.json
> +		"dayjs": "^1.11.7",
These all should be devDependencies too

2023-03-21 19:52 UTC, UltraCakeBakery commented on src/lib/components/Accordion/AccordionPanel.svelte
> +		@apply hidden p-4;
@vanillacode314 did you use an auto sorter for classes? Or just swapped these because you can? If you used a auto sorter, how does it work and where do I get it?

2023-03-21 19:52 UTC, UltraCakeBakery commented on src/hooks.server.ts
Why rename it to server? Doesn't this fuck up the SPA / PWA?

2023-03-21 19:52 UTC, UltraCakeBakery commented on src/routes/+error.svelte
> +		<img src="img/404_undraw.svg" alt="" class="select-none drag-none w-96 mx-auto my-8" />
relative path might not work on sub routes?

2023-03-21 19:52 UTC, UltraCakeBakery commented on src/routes/api/changelog/+server.ts
> +	const lang = parseCookie(request, 'lang') as string;
This works, but you could've used the new cookie api instead. Don't change this though. Refactoring that is a waste of time. Should be something for desktop clock's next major rebuild.

2023-03-21 20:23 UTC, justingolden21 commented on src/lib/components/Accordion/AccordionPanel.svelte
> +		@apply hidden p-4;
From raq:
`pnpm i prettier-plugin-organize-imports prettier-plugin-tailwindcss -D`

2023-03-21 20:55 UTC, vanillacode314 commented on package.json
> +		"dayjs": "^1.11.7",
why would dayjs be a dev deps?

2023-03-21 20:55 UTC, vanillacode314 commented on src/hooks.server.ts
new sveltekit version renamed the hooks file

2023-03-21 20:56 UTC, vanillacode314 commented on src/routes/+error.svelte
> +		<img src="img/404_undraw.svg" alt="" class="select-none drag-none w-96 mx-auto my-8" />
true

2023-03-22 05:47 UTC, merged

2023-03-22 07:01 UTC, UltraCakeBakery commented on package.json
> +		"dayjs": "^1.11.7",
They all should be devDependencies, not just daysjs. Its a general node convention. devDependencies are only required during dev (which includes the moment when the app gets build). dependencies are included when you install the app.

It does not matter for dc, but its ugly / messy. I also remember vite handling those dependencies differently, bur can't remember how exactly.

2023-03-22 07:50 UTC, vanillacode314 commented on package.json
> +		"dayjs": "^1.11.7",
It's worth it to have just for the developers benefit

2023-03-22 07:50 UTC, vanillacode314 commented on package.json
> +		"dayjs": "^1.11.7",
I mean the distinction is worth having